version: '3.8'

services:

  redis:
    image: redis:alpine
    container_name: redis_base

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    container_name: postgres_db_base

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app_base
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST} # this matched the db service name
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/django
    container_name: celery_base
    depends_on:
      - db
      - redis
      - app
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}