version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mysql_container
    ports:
      - "3306:3306"


