version: '3.8'

services:

  redis:
    image: redis:alpine
    container_name: redis_base

  db:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
    container_name: mongo_db_base
    ports:
      - 27018:27017 # If you have another mongo instance running on 27017, use another port like 27018. This port is for the outside world. 
    environment:
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_INITDB_DATABASE}
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}


  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_app_base
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - MONGO_HOST=${MONGO_HOST} # this matched the db service name
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_INITDB_DATABASE}
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_URI=${MONGO_URI}
    entrypoint: ./entrypoint.sh

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/django
    container_name: celery_base
    depends_on:
      - db
      - redis
      - app
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_INITDB_DATABASE}
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_URI=${MONGO_URI}
    entrypoint: ./entrypoint.sh # sure "chmod +x entrypoint.sh"